version: "3"

services:
  hotel-naming-server:
    build: hotel-naming-server/
    ports:
      - 8761:8761
    container_name: hotel-naming-server
      
  hotel-database:
    image: mysql
    container_name: hotel_db 
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  
    volumes:
      - ../../../MySQL/Data:/var/lib/mysql
      
  hotel-config-server:
    build: hotel-config-server/
    ports:
      - 8000:8000
    container_name: hotel-config-server
    depends_on:
      - hotel-naming-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://hotel-naming-server:8761/eureka
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULTLABEL: main
   
  hotel-inventory:
    build: inventory/
    ports: 
      - 9000:9000
    container_name: hotel-inventory
    depends_on:
      - hotel-database
      - hotel-config-server
      - hotel-naming-server
    environment:
      SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: false
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://hotel-naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://hotel-database:3306/hotel_inventory
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_JPA_HIBERNATE_DDLAUTO: update
      
  hotel-api-gateway:
    build: hotel-api-gateway/
    ports:
      - 8765:8765
    container_name: hotel-api-gateway
    depends_on:
      - hotel-database
      - hotel-config-server
      - hotel-naming-server
      - hotel-inventory
    environment:
      SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: false
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://hotel-naming-server:8761/eureka
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
      SPRING_PROFILES_ACTIVE: path
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: hotel-service
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://hotel-inventory:9000
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES: Path=/hotel/**
   